### ISSUE TITLE
amplify.hashDir is not a function

### ISSUE THREAD

**Issue by piccinnigius** [awslabs/amplify-video#143]
**Describe the bug**
when i run `amplify add/update video` the script stuck

**To Reproduce**
1. init a new amplify project
2. amplify init
3. amplify add auth
4. amplify add api
5. amplify add storage
6. amplify add video

**Expected behavior**
To add the video category to project

**exception raised**
? Choose what project you want to update? mrvideovod
? Select a system-provided encoding template, specify an already-created template name:  Default HLS Adaptive Bitrate
? Is this a production enviroment? No
? Do you want Amplify to create a new GraphQL API to manage your videos? (Beta) No
- Building video resources...amplify.hashDir is not a function
TypeError: amplify.hashDir is not a function
    at C:\Users\user\AppData\Roaming\npm\node_modules\amplify-category-video\provider-utils\awscloudformation\utils\video-staging.js:139:15
    at Array.forEach (<anonymous>)
    at generateLambdaHashes (C:\Users\user\AppData\Roaming\npm\node_modules\amplify-category-video\provider-utils\awscloudformation\utils\video-staging.js:134:11)
    at build (C:\Users\user\AppData\Roaming\npm\node_modules\amplify-category-video\provider-utils\awscloudformation\utils\video-staging.js:63:24)
    at async Object.updateResource (C:\Users\user\AppData\Roaming\npm\node_modules\amplify-category-video\provider-utils\awscloudformation\index.js:41:3)
    at async Object.executeAmplifyCommand (C:\Users\user\AppData\Roaming\npm\node_modules\amplify-category-video\index.js:78:3)
    at async executePluginModuleCommand (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:131:13)
    at async Object.executeCommand (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\execution-manager.js:16:9)
    at async Object.run (C:\Users\user\AppData\Roaming\npm\node_modules\@aws-amplify\cli\lib\index.js:43:9)      
| Building video `resources...

when i run `amplify update` i got:
@auth directive with 'userPools' provider found, but the project has no Cognito User Pools authentication provider configured.

but the userpool is configured

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox

**Comment by wizage** [comment]
Please update your version of Amplify.

If it is up to date please post the results of:

```amplify -v```
```amplify video -v```

**Comment by piccinnigius** [comment]
oh, removing and reinstall amplify fixes this (i have troubles with npm)
