### ISSUE TITLE
Amplify video add Error

### ISSUE THREAD

**Issue by oscarmendozavargas** [awslabs/amplify-video#15]
After running the command: amplify video add , I got the following error:
C:\Users\menosc\AppData\Roaming\npm\node_modules\@aws-amplify\cli\node_modules\gluegun\build\index.js:13
    throw up;
    ^

Error: AdminPanelNew is present in amplify-meta.json
    at Object.updateamplifyMetaAfterResourceAdd (C:\Users\menosc\AppData\Roaming\npm\node_modules\@aws-amplify\cli\src\extensions\amplify-helpers\update-amplify-meta.js:84:11)
    at copyFilesToLocal (C:\Users\menosc\AppData\Roaming\npm\node_modules\amplify-category-video\extensions\livestream-push.js:153:21)
    at addLivestream (C:\Users\menosc\AppData\Roaming\npm\node_modules\amplify-category-video\extensions\livestream-push.js:89:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by wizage** [comment]
Issue moved to Amplify Video as it is an issue with Amplify Video. I am looking into it!

Thanks,
Sam Patzer

**Comment by wizage** [comment]
Issue has been resolved.

The problem was that the same project name existed in the project causing issues.

**Comment by cdeavila** [comment]
Hello everyone, I have another problem with that same command amplify add video, when executing it it indicates the following error: ⚠️ The Amplify CLI can NOT find command: add video, I have tried to correct it following several solutions but it has not been possible, could you please help me.
