### ISSUE TITLE
Can not push to amplify when updating to v3.9.2

### ISSUE THREAD

**Issue by maupeon** [awslabs/amplify-video#335]
**Describe the bug**
I am trying to push a new version of amplify-category video
And when I push, this is the message I receive:

Cannot read property 'snsFunction' of undefined date=Fri Feb 11 2022 14:01:31 GMT-0600 (Central Standard Time), pid=89220, uid=501, gid=20, cwd=/Users/maupeon/Documents/Trabajo/MEDU/Sistemas/medu_2, execPath=/usr/local/bin/node, version=v14.18.1, argv=[/usr/local/bin/node, /usr/local/bin/amplify, push], rss=652808192, heapTotal=553140224, heapUsed=510996208, external=140920011, arrayBuffers=138661983, loadavg=[14.6279296875, 5.888671875, 4.720703125], uptime=1463032, trace=[column=12, file=/usr/local/lib/node_modules/amplify-category-video/node_modules/ejs/lib/ejs.js, function=eval (eval at compile, line=652, method=null, native=false, column=17, file=/usr/local/lib/node_modules/amplify-category-video/node_modules/ejs/lib/ejs.js, function=anonymous, line=682, method=null, native=false, column=37, file=/usr/local/lib/node_modules/amplify-category-video/node_modules/ejs/lib/ejs.js, function=Object.exports.render, line=419, method=render, native=false, column=25, file=/usr/local/lib/node_modules/amplify-category-video/provider-utils/awscloudformation/utils/video-staging.js, function=handleEJS, line=365, method=null, native=false, column=7, file=/usr/local/lib/node_modules/amplify-category-video/provider-utils/awscloudformation/utils/video-staging.js, function=Object.filterForEJS [as filter], line=256, method=filterForEJS [as filter], native=false, column=24, file=/usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js, function=handleFilter, line=51, method=null, native=false, column=27, file=/usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js, function=startCopy, line=61, method=null, native=false, column=5, file=/usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js, function=null, line=160, method=null, native=false, column=12, file=/usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js, function=null, line=242, method=null, native=false, column=43, file=/usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js, function=null, line=224, method=null, native=false, column=20, file=/usr/local/lib/node_modules/amplify-category-video/node_modules/graceful-fs/polyfills.js, function=callback, line=299, method=null, native=false, column=21, file=fs.js, function=FSReqCallback.oncomplete, line=191, method=oncomplete, native=false], stack=[TypeError: ejs:83,     81|               Service : 'events.amazonaws.com',     82|             Resource: !Ref MediaConvertNotificationsSNS,  >> 83| <% if (props.sns.snsFunction) { -%>,     84|   rMediaconvertStatusLambda:,     85|     Type: AWS::Lambda::Function,     86|     Properties:, , Cannot read property 'snsFunction' of undefined,     at eval (eval at compile (/usr/local/lib/node_modules/amplify-category-video/node_modules/ejs/lib/ejs.js:652:12), <anonymous>:18:22),     at anonymous (/usr/local/lib/node_modules/amplify-category-video/node_modules/ejs/lib/ejs.js:682:17),     at Object.exports.render (/usr/local/lib/node_modules/amplify-category-video/node_modules/ejs/lib/ejs.js:419:37),     at handleEJS (/usr/local/lib/node_modules/amplify-category-video/provider-utils/awscloudformation/utils/video-staging.js:365:25),     at Object.filterForEJS [as filter] (/usr/local/lib/node_modules/amplify-category-video/provider-utils/awscloudformation/utils/video-staging.js:256:7),     at handleFilter (/usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js:51:24),     at startCopy (/usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js:61:27),     at /usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js:160:5,     at /usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js:242:12,     at /usr/local/lib/node_modules/amplify-category-video/node_modules/fs-extra/lib/copy/copy.js:224:43,     at callback (/usr/local/lib/node_modules/amplify-category-video/node_modules/graceful-fs/polyfills.js:299:20),     at FSReqCallback.oncomplete (fs.js:191:21)]

**Expected behavior**
I expect to push all my changes to amplify

**Desktop (please complete the following information):**
MacOs Monterey
Version 12.0.1

PLEASE HELP, AMPLIFY NEEDS THIS

**Comment by shamikatamazon** [comment]
Hi @maupeon - please can you provide the values of the questionnaire before you did the push ?
